version: '3.8'

services:
  orderservice-api:
    build:
      context: .
      dockerfile: src/OrdersService.Api/Dockerfile
    ports:
      - "8080:8080"  # Mapea el puerto 80 del contenedor al 5000 de la máquina host
    depends_on:
      - dynamodb
      - localstack
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Variables para que la API se comunique con los contenedores
      - DynamoDB__ServiceURL=http://dynamodb:8000
      - SQS__ServiceURL=http://localstack:4566
    command: >
      /bin/bash -c "until curl -s http://dynamodb:8000; do echo 'Esperando a DynamoDB...'; sleep 2; done;
      until curl -s http://localstack:4566; do echo 'Esperando a LocalStack...'; sleep 2; done;
      dotnet run --project src/OrdersService.Api"

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs,dynamodb
      - DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Permite a LocalStack interactuar con Docker
